name: Prkr
main: com.luzinsk.prkr.Prkr
version: 1.0
description: Parkour plugin for checkpoints & speedruns
author: Ethan Pilz, Carlton Wu
commands:
  prkr:
    description: Prkr commands
  setcp:
    description: Set checkpoint
  cp:
    description: Teleport to checkpoint
permissions:
  Prkr.setcp:
    description: Allows user to set a checkpoint
    default: true